# Generated by Django 3.2.20 on 2023-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='locations',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
