# Generated by Django 3.2.20 on 2023-08-09 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stops', '0002_rename_stops_stop'),
        ('journeys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.journey')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='stops.stop')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'journey', 'stop')},
            },
        ),
    ]
