# Generated by Django 3.2.20 on 2023-08-10 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stops', '0007_remove_stop_journey'),
        ('likes_stops', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likestop',
            unique_together={('owner', 'stop')},
        ),
        migrations.RemoveField(
            model_name='likestop',
            name='journey',
        ),
    ]
