# Generated by Django 3.2.20 on 2023-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='countries',
            field=models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='journey',
            name='locations',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
