# Generated by Django 3.2.20 on 2023-08-09 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stops',
            new_name='Stop',
        ),
    ]
